#include<stdio.h>
#include<conio.h>
#include<windows.h>
main(){

	for(int a=1; a<=60; a++){
gotoxy(9+a,11);printf("          $$$$$$$$$$$$$$$$$$$$$$$$$\n");Sleep(1);
gotoxy(9+a,12);printf("         $$$$ $$$$$$$$$$$$$$$$$$$$$$\n");Sleep(1);
gotoxy(9+a,13);printf("        $$$$   $$$$$$$$$$$$$$$$$$$$$$\n");Sleep(1);
gotoxy(9+a,14);printf("      $$$$      $$$$$$$$$$$$$$$$$$$$$$$\n");Sleep(1);
gotoxy(9+a,15);printf("    $$$$$        $$$$$$$$$$$$$$$$$$$$$$$\n");Sleep(1);
gotoxy(9+a,16);printf("   $$$$$          $$$$$$$$$$$$$$$$$$$$$$$\n");Sleep(1);
gotoxy(9+a,17);printf("  $$$$$            $$$$$$$$$$$$$$$$$$$$$$$\n");Sleep(1);
gotoxy(9+a,18);printf(" $$$$$$            $$$$$$$$$$$$$$$$$$$$$$$$\n");Sleep(1);
gotoxy(9+a,19);printf(" $$$$$$           $$$$$$$$$           $$$$$$\n");Sleep(1);
gotoxy(9+a,20);printf(" $$$$$$$         $$$ $$$ $$$         $$$$$$$\n");Sleep(1);
gotoxy(9+a,21);printf(" $$$$$$$$      $$$$   $   $$$$      $$$$$$$$\n");Sleep(1);
gotoxy(9+a,22);printf(" $$$$$$$$$$$$$$$$$   $$$   $$$$$$$$$$$$$$$$$\n");Sleep(1);
gotoxy(9+a,22);printf(" $$$ $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ o$$\n");Sleep(1);
gotoxy(9+a,23);printf(" $$$  $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$  $$$\n");Sleep(1);
gotoxy(9+a,24);printf("  $$$  $’$$$$$$$$$$$$$$$$$$$$$$$$$$$$$  o$$$\n");Sleep(1);
gotoxy(9+a,24);printf("  ’$$o  $$  $$’$$$$$$$$$$$$$$’$$  $$     o$$\n");Sleep(1);
gotoxy(9+a,25);printf("    $$o$    $$  ’$$’$$’$$’  $$     $   o$$\n");Sleep(1);
gotoxy(9+a,25);printf("     $$$o$  $    $$    $$   $$    $$  o$\n");Sleep(1);
gotoxy(9+a,26);printf("      ’$$$$O$    $$    $$   $$     o$$$\n");Sleep(1);
gotoxy(9+a,27);printf("         ’$$o$$  $$    $$   $$   o$$$\n");Sleep(1);
gotoxy(9+a,28);printf("           ’$$$$o$o$o$o$o$o$o$o$$$$\n");Sleep(1);
gotoxy(9+a,29);printf("             ’$$$$o$o$o$o$o$o$o$o\n");Sleep(1);
	}

getch();
}